!!python/object/apply:types.SimpleNamespace
state:
  adf_loss_weight: 0
  adjoint: true
  allow_off_policy_updates: false
  amp: false
  angle_range:
  - 0
  - 180
  bond_dev_tol: 0.25
  checkpoint: null
  checkpoint_epoch: -1
  cpu: false
  diameter_viz: 0.08
  diffusion_loss_weight: 0
  diffusion_window: 1000
  distributed: false
  distributed_backend: nccl
  distributed_port: 13356
  dr: 0.02
  dv: 0.1
  energy_force_loss_weight: 10
  eq_steps: 0
  eval_model: lmax=2
  exp_name: FINAL
  gaussian_width: 0.01
  gradient_clipping: true
  ic_stddev: 0.0
  identifier: ''
  integrator: NoseHoover
  is_debug: false
  l_max: 1
  local_rank: 0
  log_dir: /global/cfs/projectdirs/m4319/sanjeevr
  lr: 0.001
  max_frac_unstable_threshold: 0.75
  max_rdf_dist: 15
  max_times_reduce_lr: 2
  min_frac_unstable_threshold: 0.0
  minibatch_size: 40
  mode: train
  model: nequip
  model_dir: /pscratch/sd/s/sanjeevr/MODELPATH
  molecule: ac_Ala3_NHMe
  n_dump: 100
  n_dump_vacf: 2
  n_epochs: 600
  n_replicas: 128
  name: md22
  noddp: false
  normalize_labels: false
  only_learn_if_unstable_threshold_reached: true
  only_train_on_unstable_replicas: false
  optimizer: SGD
  print_every: 200
  rdf_loss_weight: 1
  reset_probability: 0.05
  results_dir: /global/cfs/projectdirs/m4319/sanjeevr/results_md22_final_l=1_25percent
  run_dir: MODELPATH/
  seed: 0
  shuffle: true
  size: 25percent
  src: /pscratch/sd/s/sanjeevr
  steps: 2000
  submit: false
  summit: false
  timestamp_id: null
  train: true
  training_observable: rdf
  use_mse_gradient: true
  vacf_loss_weight: 0
  vacf_window: 100
  world_size: 1
