!!python/object/apply:types.SimpleNamespace
state:
  adf_loss_weight: 0
  adjoint: true
  allow_off_policy_updates: false
  amp: false
  angle_range:
  - 0
  - 180
  checkpoint: null
  checkpoint_epoch: -1
  cpu: false
  diameter_viz: 0.08
  diffusion_loss_weight: 0
  diffusion_window: 1000
  distributed: false
  distributed_backend: nccl
  distributed_port: 13356
  dr: 0.24
  dv: 0.1
  energy_force_loss_weight: 0
  eq_steps: 0
  eval_model: post
  exp_name: TEST_bond_length_dev_singlemolecule
  gaussian_width: 0.01
  grad_clip_norm_threshold: 1.0
  gradient_clipping: true
  ic_stddev: 0.0
  identifier: ''
  imd_tol: 1.2
  integrator: NoseHoover
  integrator_config:
    gamma: 0.1
    timestep: 1.0
    ttime: 20.0
  is_debug: false
  l_max: 3
  local_rank: 0
  log_dir: /global/cfs/projectdirs/m4319/sanjeevr
  lr: 0.003
  max_frac_unstable_threshold: 0.75
  max_rdf_dist: 6
  max_times_reduce_lr: 2
  min_frac_unstable_threshold: 0
  minibatch_size: 4
  mode: train
  model: gemnet_t
  model_dir: /pscratch/sd/s/sanjeevr/MODELPATH
  n_closest_molecules: 0
  n_dump: 100
  n_dump_vacf: 2
  n_epochs: 500
  n_local_neighborhoods: 64
  n_replicas: 8
  name: water
  noddp: false
  normalize_labels: false
  only_learn_if_unstable_threshold_reached: true
  only_train_on_unstable_replicas: false
  optimizer: SGD
  print_every: 200
  rdf_loss_weight: 1
  reset_probability: 0.0
  results_dir: /global/cfs/projectdirs/m4319/sanjeevr/results_water_localneighborhoods
  run_dir: MODELPATH/
  seed: 0
  shuffle: true
  size: 1k
  src: /pscratch/sd/s/sanjeevr
  stability_criterion: imd
  steps: 1000
  submit: false
  summit: false
  temperature: 300.0
  timestamp_id: null
  train: true
  training_observable: bond_length_dev
  use_mse_gradient: true
  vacf_loss_weight: 0
  vacf_window: 100
  world_size: 1
