amp: false
checkpoint: null
cpu: false
dataset:
- grad_target_mean: 0.0
  grad_target_std: 1.0
  molecule: aspirin
  name: md17-aspirin
  normalize_labels: true
  size: 1k
  src: post_data/md17/aspirin/1k/train
  target_mean: -17637.827343506295
  target_std: 1.0
- src: post_data/md17/aspirin/1k/val
distributed: false
distributed_backend: nccl
distributed_port: 13356
identifier: ''
is_debug: false
local_rank: 0
logger:
  name: wandb
  project: mdbench
mode: train
model:
  cutoff: 5.0
  hidden_channels: 64
  name: schnet
  num_filters: 64
  num_gaussians: 25
  num_interactions: 6
  otf_graph: true
  use_pbc: false
noddp: false
optim:
  batch_size: 100
  checkpoint_every: 10
  early_stopping_lr: 1.0e-06
  early_stopping_time: 604800
  energy_coefficient: 0.05
  eval_batch_size: 100
  factor: 0.8
  force_coefficient: 0.95
  lr_gamma: 0.1
  lr_initial: 0.001
  max_epochs: 10000
  min_lr: 1.0e-06
  num_workers: 8
  optimizer: Adam
  patience: 5
  scheduler: ReduceLROnPlateau
  warmup_factor: 0.2
  warmup_steps: 5000
print_every: 200
run_dir: MODELPATH/
seed: 0
submit: false
summit: false
task:
  dataset: lmdb
  description: Regressing to energies and forces
  eval_on_free_atoms: true
  grad_input: atomic forces
  labels:
  - potential energy
  metric: mae
  train_on_free_atoms: true
  type: regression
timestamp_id: null
trainer: trainer
world_size: 1
